#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

[ -n "$CI" ] && exit 0

remote="$1"
url="$2"

echo "checking remote url... $url"

if echo "$url" | grep -q "obnizjs-for-admin"; then
  # continue push
  exit 0
else
  cat <<-EOS
  --------------------------------------------------

  DO NOT PUSH TO $url. It's maybe obnizjs-for-admin script.

  --------------------------------------------------
EOS
  # cancel push
  exit 1
fi
