// Generated By devtools/_tools/generateBleUuids.js

export const ServiceUuids = {
  /** Generic Access Service (0x1800) */
  generic_access: '1800',
  /** Generic Attribute Service (0x1801) */
  generic_attribute: '1801',
  /** Immediate Alert Service (0x1802) */
  immediate_alert: '1802',
  /** Link Loss Service (0x1803) */
  link_loss: '1803',
  /** Tx Power Service (0x1804) */
  tx_power: '1804',
  /** Current Time Service (0x1805) */
  current_time: '1805',
  /** Reference Time Update Service (0x1806) */
  reference_time_update: '1806',
  /** Next DST Change Service (0x1807) */
  next_dst_change: '1807',
  /** Glucose Service (0x1808) */
  glucose: '1808',
  /** Health Thermometer Service (0x1809) */
  health_thermometer: '1809',
  /** Device Information Service (0x180A) */
  device_information: '180a',
  /** Heart Rate Service (0x180D) */
  heart_rate: '180d',
  /** Phone Alert Status Service (0x180E) */
  phone_alert_status: '180e',
  /** Battery Service (0x180F) */
  battery_service: '180f',
  /** Blood Pressure Service (0x1810) */
  blood_pressure: '1810',
  /** Alert Notification Service (0x1811) */
  alert_notification: '1811',
  /** Human Interface Device Service (0x1812) */
  human_interface_device: '1812',
  /** Scan Parameters Service (0x1813) */
  scan_parameters: '1813',
  /** Running Speed and Cadence Service (0x1814) */
  running_speed_and_cadence: '1814',
  /** Automation IO Service (0x1815) */
  automation_io: '1815',
  /** Cycling Speed and Cadence Service (0x1816) */
  cycling_speed_and_cadence: '1816',
  /** Cycling Power Service (0x1818) */
  cycling_power: '1818',
  /** Location and Navigation Service (0x1819) */
  location_and_navigation: '1819',
  /** Environmental Sensing Service (0x181A) */
  environmental_sensing: '181a',
  /** Body Composition Service (0x181B) */
  body_composition: '181b',
  /** User Data Service (0x181C) */
  user_data: '181c',
  /** Weight Scale Service (0x181D) */
  weight_scale: '181d',
  /** Bond Management Service (0x181E) */
  bond_management: '181e',
  /** Continuous Glucose Monitoring Service (0x181F) */
  continuous_glucose_monitoring: '181f',
  /** Internet Protocol Support Service (0x1820) */
  internet_protocol_support: '1820',
  /** Indoor Positioning Service (0x1821) */
  indoor_positioning: '1821',
  /** Pulse Oximeter Service (0x1822) */
  pulse_oximeter: '1822',
  /** HTTP Proxy Service (0x1823) */
  http_proxy: '1823',
  /** Transport Discovery Service (0x1824) */
  transport_discovery: '1824',
  /** Object Transfer Service (0x1825) */
  object_transfer: '1825',
  /** Fitness Machine Service (0x1826) */
  fitness_machine: '1826',
  /** Mesh Provisioning Service (0x1827) */
  mesh_provisioning: '1827',
  /** Mesh Proxy Service (0x1828) */
  mesh_proxy: '1828',
  /** Reconnection Configuration Service (0x1829) */
  reconnection_configuration: '1829',
  /** Insulin Delivery Service (0x183A) */
  insulin_delivery: '183a',
  /** Binary Sensor Service (0x183B) */
  binary_sensor: '183b',
  /** Emergency Configuration Service (0x183C) */
  emergency_configuration: '183c',
  /** Authorization Control Service (0x183D) */
  authorization_control: '183d',
  /** Physical Activity Monitor Service (0x183E) */
  physical_activity_monitor: '183e',
  /** Elapsed Time Service (0x183F) */
  elapsed_time: '183f',
  /** Generic Health Sensor Service (0x1840) */
  generic_health_sensor: '1840',
  /** Audio Input Control Service (0x1843) */
  audio_input_control: '1843',
  /** Volume Control Service (0x1844) */
  volume_control: '1844',
  /** Volume Offset Control Service (0x1845) */
  volume_offset: '1845',
  /** Coordinated Set Identification Service (0x1846) */
  coordinated_set_identification: '1846',
  /** Device Time Service (0x1847) */
  device_time: '1847',
  /** Media Control Service (0x1848) */
  media_control: '1848',
  /** Generic Media Control Service (0x1849) */
  generic_media_control: '1849',
  /** Constant Tone Extension Service (0x184A) */
  constant_tone_extension: '184a',
  /** Telephone Bearer Service (0x184B) */
  telephone_bearer: '184b',
  /** Generic Telephone Bearer Service (0x184C) */
  generic_telephone_bearer: '184c',
  /** Microphone Control Service (0x184D) */
  microphone_control: '184d',
  /** Audio Stream Control Service (0x184E) */
  audio_stream_control: '184e',
  /** Broadcast Audio Scan Service (0x184F) */
  broadcast_audio_scan: '184f',
  /** Published Audio Capabilities Service (0x1850) */
  published_audio_capabilities: '1850',
  /** Basic Audio Announcement Service (0x1851) */
  basic_audio_announcement: '1851',
  /** Broadcast Audio Announcement Service (0x1852) */
  broadcast_audio_announcement: '1852',
  /** Common Audio Service (0x1853) */
  common_audio: '1853',
  /** Hearing Access Service (0x1854) */
  hearing_access: '1854',
  /** Telephony and Media Audio Service (0x1855) */
  telephony_and_media_audio: '1855',
  /** Public Broadcast Announcement Service (0x1856) */
  public_broadcast_announcement: '1856',
  /** Electronic Shelf Label Service (0x1857) */
  electronic_shelf_label: '1857',
} as const;

export const CharUuids = {
  /** Device Name Characteristic (0x2A00) */
  device_name: '2a00',
  /** Appearance Characteristic (0x2A01) */
  appearance: '2a01',
  /** Peripheral Privacy Flag Characteristic (0x2A02) */
  peripheral_privacy_flag: '2a02',
  /** Reconnection Address Characteristic (0x2A03) */
  reconnection_address: '2a03',
  /** Peripheral Preferred Connection Parameters Characteristic (0x2A04) */
  peripheral_preferred_connection_parameters: '2a04',
  /** Service Changed Characteristic (0x2A05) */
  service_changed: '2a05',
  /** Alert Level Characteristic (0x2A06) */
  alert_level: '2a06',
  /** Tx Power Level Characteristic (0x2A07) */
  tx_power_level: '2a07',
  /** Date Time Characteristic (0x2A08) */
  date_time: '2a08',
  /** Day of Week Characteristic (0x2A09) */
  day_of_week: '2a09',
  /** Day Date Time Characteristic (0x2A0A) */
  day_date_time: '2a0a',
  /** Exact Time 256 Characteristic (0x2A0C) */
  exact_time_256: '2a0c',
  /** DST Offset Characteristic (0x2A0D) */
  dst_offset: '2a0d',
  /** Time Zone Characteristic (0x2A0E) */
  time_zone: '2a0e',
  /** Local Time Information Characteristic (0x2A0F) */
  local_time_information: '2a0f',
  /** Time with DST Characteristic (0x2A11) */
  time_with_dst: '2a11',
  /** Time Accuracy Characteristic (0x2A12) */
  time_accuracy: '2a12',
  /** Time Source Characteristic (0x2A13) */
  time_source: '2a13',
  /** Reference Time Information Characteristic (0x2A14) */
  reference_time_information: '2a14',
  /** Time Update Control Point Characteristic (0x2A16) */
  time_update_control_point: '2a16',
  /** Time Update State Characteristic (0x2A17) */
  time_update_state: '2a17',
  /** Glucose Measurement Characteristic (0x2A18) */
  glucose_measurement: '2a18',
  /** Battery Level Characteristic (0x2A19) */
  battery_level: '2a19',
  /** Temperature Measurement Characteristic (0x2A1C) */
  temperature_measurement: '2a1c',
  /** Temperature Type Characteristic (0x2A1D) */
  temperature_type: '2a1d',
  /** Intermediate Temperature Characteristic (0x2A1E) */
  intermediate_temperature: '2a1e',
  /** Measurement Interval Characteristic (0x2A21) */
  measurement_interval: '2a21',
  /** Boot Keyboard Input Report Characteristic (0x2A22) */
  boot_keyboard_input_report: '2a22',
  /** System ID Characteristic (0x2A23) */
  system_id: '2a23',
  /** Model Number String Characteristic (0x2A24) */
  model_number_string: '2a24',
  /** Serial Number String Characteristic (0x2A25) */
  serial_number_string: '2a25',
  /** Firmware Revision String Characteristic (0x2A26) */
  firmware_revision_string: '2a26',
  /** Hardware Revision String Characteristic (0x2A27) */
  hardware_revision_string: '2a27',
  /** Software Revision String Characteristic (0x2A28) */
  software_revision_string: '2a28',
  /** Manufacturer Name String Characteristic (0x2A29) */
  manufacturer_name_string: '2a29',
  /** IEEE 11073-20601 Regulatory Certification Data List Characteristic (0x2A2A) */
  ieee_11073_20601_regulatory_certification_data_list: '2a2a',
  /** Current Time Characteristic (0x2A2B) */
  current_time: '2a2b',
  /** Magnetic Declination Characteristic (0x2A2C) */
  magnetic_declination: '2a2c',
  /** Scan Refresh Characteristic (0x2A31) */
  scan_refresh: '2a31',
  /** Boot Keyboard Output Report Characteristic (0x2A32) */
  boot_keyboard_output_report: '2a32',
  /** Boot Mouse Input Report Characteristic (0x2A33) */
  boot_mouse_input_report: '2a33',
  /** Glucose Measurement Context Characteristic (0x2A34) */
  glucose_measurement_context: '2a34',
  /** Blood Pressure Measurement Characteristic (0x2A35) */
  blood_pressure_measurement: '2a35',
  /** Intermediate Cuff Pressure Characteristic (0x2A36) */
  intermediate_cuff_pressure: '2a36',
  /** Heart Rate Measurement Characteristic (0x2A37) */
  heart_rate_measurement: '2a37',
  /** Body Sensor Location Characteristic (0x2A38) */
  body_sensor_location: '2a38',
  /** Heart Rate Control Point Characteristic (0x2A39) */
  heart_rate_control_point: '2a39',
  /** Alert Status Characteristic (0x2A3F) */
  alert_status: '2a3f',
  /** Ringer Control Point Characteristic (0x2A40) */
  ringer_control_point: '2a40',
  /** Ringer Setting Characteristic (0x2A41) */
  ringer_setting: '2a41',
  /** Alert Category ID Bit Mask Characteristic (0x2A42) */
  alert_category_id_bit_mask: '2a42',
  /** Alert Category ID Characteristic (0x2A43) */
  alert_category_id: '2a43',
  /** Alert Notification Control Point Characteristic (0x2A44) */
  alert_notification_control_point: '2a44',
  /** Unread Alert Status Characteristic (0x2A45) */
  unread_alert_status: '2a45',
  /** New Alert Characteristic (0x2A46) */
  new_alert: '2a46',
  /** Supported New Alert Category Characteristic (0x2A47) */
  supported_new_alert_category: '2a47',
  /** Supported Unread Alert Category Characteristic (0x2A48) */
  supported_unread_alert_category: '2a48',
  /** Blood Pressure Feature Characteristic (0x2A49) */
  blood_pressure_feature: '2a49',
  /** HID Information Characteristic (0x2A4A) */
  hid_information: '2a4a',
  /** Report Map Characteristic (0x2A4B) */
  report_map: '2a4b',
  /** HID Control Point Characteristic (0x2A4C) */
  hid_control_point: '2a4c',
  /** Report Characteristic (0x2A4D) */
  report: '2a4d',
  /** Protocol Mode Characteristic (0x2A4E) */
  protocol_mode: '2a4e',
  /** Scan Interval Window Characteristic (0x2A4F) */
  scan_interval_window: '2a4f',
  /** PnP ID Characteristic (0x2A50) */
  pnp_id: '2a50',
  /** Glucose Feature Characteristic (0x2A51) */
  glucose_feature: '2a51',
  /** Record Access Control Point Characteristic (0x2A52) */
  record_access_control_point: '2a52',
  /** RSC Measurement Characteristic (0x2A53) */
  rsc_measurement: '2a53',
  /** RSC Feature Characteristic (0x2A54) */
  rsc_feature: '2a54',
  /** SC Control Point Characteristic (0x2A55) */
  sc_control_point: '2a55',
  /** Aggregate Characteristic (0x2A5A) */
  aggregate: '2a5a',
  /** CSC Measurement Characteristic (0x2A5B) */
  csc_measurement: '2a5b',
  /** CSC Feature Characteristic (0x2A5C) */
  csc_feature: '2a5c',
  /** Sensor Location Characteristic (0x2A5D) */
  sensor_location: '2a5d',
  /** PLX Spot-Check Measurement Characteristic (0x2A5E) */
  plx_spot_check_measurement: '2a5e',
  /** PLX Continuous Measurement Characteristic (0x2A5F) */
  plx_continuous_measurement: '2a5f',
  /** PLX Features Characteristic (0x2A60) */
  plx_features: '2a60',
  /** Cycling Power Measurement Characteristic (0x2A63) */
  cycling_power_measurement: '2a63',
  /** Cycling Power Vector Characteristic (0x2A64) */
  cycling_power_vector: '2a64',
  /** Cycling Power Feature Characteristic (0x2A65) */
  cycling_power_feature: '2a65',
  /** Cycling Power Control Point Characteristic (0x2A66) */
  cycling_power_control_point: '2a66',
  /** Location and Speed Characteristic (0x2A67) */
  location_and_speed: '2a67',
  /** Navigation Characteristic (0x2A68) */
  navigation: '2a68',
  /** Position Quality Characteristic (0x2A69) */
  position_quality: '2a69',
  /** LN Feature Characteristic (0x2A6A) */
  ln_feature: '2a6a',
  /** LN Control Point Characteristic (0x2A6B) */
  ln_control_point: '2a6b',
  /** Elevation Characteristic (0x2A6C) */
  elevation: '2a6c',
  /** Pressure Characteristic (0x2A6D) */
  pressure: '2a6d',
  /** Temperature Characteristic (0x2A6E) */
  temperature: '2a6e',
  /** Humidity Characteristic (0x2A6F) */
  humidity: '2a6f',
  /** True Wind Speed Characteristic (0x2A70) */
  true_wind_speed: '2a70',
  /** True Wind Direction Characteristic (0x2A71) */
  true_wind_direction: '2a71',
  /** Apparent Wind Speed Characteristic (0x2A72) */
  apparent_wind_speed: '2a72',
  /** Apparent Wind Direction Characteristic (0x2A73) */
  apparent_wind_direction: '2a73',
  /** Gust Factor Characteristic (0x2A74) */
  gust_factor: '2a74',
  /** Pollen Concentration Characteristic (0x2A75) */
  pollen_concentration: '2a75',
  /** UV Index Characteristic (0x2A76) */
  uv_index: '2a76',
  /** Irradiance Characteristic (0x2A77) */
  irradiance: '2a77',
  /** Rainfall Characteristic (0x2A78) */
  rainfall: '2a78',
  /** Wind Chill Characteristic (0x2A79) */
  wind_chill: '2a79',
  /** Heat Index Characteristic (0x2A7A) */
  heat_index: '2a7a',
  /** Dew Point Characteristic (0x2A7B) */
  dew_point: '2a7b',
  /** Descriptor Value Changed Characteristic (0x2A7D) */
  descriptor_value_changed: '2a7d',
  /** Aerobic Heart Rate Lower Limit Characteristic (0x2A7E) */
  aerobic_heart_rate_lower_limit: '2a7e',
  /** Aerobic Threshold Characteristic (0x2A7F) */
  aerobic_threshold: '2a7f',
  /** Age Characteristic (0x2A80) */
  age: '2a80',
  /** Anaerobic Heart Rate Lower Limit Characteristic (0x2A81) */
  anaerobic_heart_rate_lower_limit: '2a81',
  /** Anaerobic Heart Rate Upper Limit Characteristic (0x2A82) */
  anaerobic_heart_rate_upper_limit: '2a82',
  /** Anaerobic Threshold Characteristic (0x2A83) */
  anaerobic_threshold: '2a83',
  /** Aerobic Heart Rate Upper Limit Characteristic (0x2A84) */
  aerobic_heart_rate_upper_limit: '2a84',
  /** Date of Birth Characteristic (0x2A85) */
  date_of_birth: '2a85',
  /** Date of Threshold Assessment Characteristic (0x2A86) */
  date_of_threshold_assessment: '2a86',
  /** Email Address Characteristic (0x2A87) */
  email_address: '2a87',
  /** Fat Burn Heart Rate Lower Limit Characteristic (0x2A88) */
  fat_burn_heart_rate_lower_limit: '2a88',
  /** Fat Burn Heart Rate Upper Limit Characteristic (0x2A89) */
  fat_burn_heart_rate_upper_limit: '2a89',
  /** First Name Characteristic (0x2A8A) */
  first_name: '2a8a',
  /** Five Zone Heart Rate Limits Characteristic (0x2A8B) */
  five_zone_heart_rate_limits: '2a8b',
  /** Gender Characteristic (0x2A8C) */
  gender: '2a8c',
  /** Heart Rate Max Characteristic (0x2A8D) */
  heart_rate_max: '2a8d',
  /** Height Characteristic (0x2A8E) */
  height: '2a8e',
  /** Hip Circumference Characteristic (0x2A8F) */
  hip_circumference: '2a8f',
  /** Last Name Characteristic (0x2A90) */
  last_name: '2a90',
  /** Maximum Recommended Heart Rate Characteristic (0x2A91) */
  maximum_recommended_heart_rate: '2a91',
  /** Resting Heart Rate Characteristic (0x2A92) */
  resting_heart_rate: '2a92',
  /** Sport Type for Aerobic and Anaerobic Thresholds Characteristic (0x2A93) */
  sport_type_for_aerobic_and_anaerobic_thresholds: '2a93',
  /** Three Zone Heart Rate Limits Characteristic (0x2A94) */
  three_zone_heart_rate_limits: '2a94',
  /** Two Zone Heart Rate Limits Characteristic (0x2A95) */
  two_zone_heart_rate_limits: '2a95',
  /** VO2 Max Characteristic (0x2A96) */
  vo2_max: '2a96',
  /** Waist Circumference Characteristic (0x2A97) */
  waist_circumference: '2a97',
  /** Weight Characteristic (0x2A98) */
  weight: '2a98',
  /** Database Change Increment Characteristic (0x2A99) */
  database_change_increment: '2a99',
  /** User Index Characteristic (0x2A9A) */
  user_index: '2a9a',
  /** Body Composition Feature Characteristic (0x2A9B) */
  body_composition_feature: '2a9b',
  /** Body Composition Measurement Characteristic (0x2A9C) */
  body_composition_measurement: '2a9c',
  /** Weight Measurement Characteristic (0x2A9D) */
  weight_measurement: '2a9d',
  /** Weight Scale Feature Characteristic (0x2A9E) */
  weight_scale_feature: '2a9e',
  /** User Control Point Characteristic (0x2A9F) */
  user_control_point: '2a9f',
  /** Magnetic Flux Density - 2D Characteristic (0x2AA0) */
  magnetic_flux_density_2d: '2aa0',
  /** Magnetic Flux Density - 3D Characteristic (0x2AA1) */
  magnetic_flux_density_3d: '2aa1',
  /** Language Characteristic (0x2AA2) */
  language: '2aa2',
  /** Barometric Pressure Trend Characteristic (0x2AA3) */
  barometric_pressure_trend: '2aa3',
  /** Bond Management Control Point Characteristic (0x2AA4) */
  bond_management_control_point: '2aa4',
  /** Bond Management Feature Characteristic (0x2AA5) */
  bond_management_feature: '2aa5',
  /** Central Address Resolution Characteristic (0x2AA6) */
  central_address_resolution: '2aa6',
  /** CGM Measurement Characteristic (0x2AA7) */
  cgm_measurement: '2aa7',
  /** CGM Feature Characteristic (0x2AA8) */
  cgm_feature: '2aa8',
  /** CGM Status Characteristic (0x2AA9) */
  cgm_status: '2aa9',
  /** CGM Session Start Time Characteristic (0x2AAA) */
  cgm_session_start_time: '2aaa',
  /** CGM Session Run Time Characteristic (0x2AAB) */
  cgm_session_run_time: '2aab',
  /** CGM Specific Ops Control Point Characteristic (0x2AAC) */
  cgm_specific_ops_control_point: '2aac',
  /** Indoor Positioning Configuration Characteristic (0x2AAD) */
  indoor_positioning_configuration: '2aad',
  /** Latitude Characteristic (0x2AAE) */
  latitude: '2aae',
  /** Longitude Characteristic (0x2AAF) */
  longitude: '2aaf',
  /** Local North Coordinate Characteristic (0x2AB0) */
  local_north_coordinate: '2ab0',
  /** Local East Coordinate Characteristic (0x2AB1) */
  local_east_coordinate: '2ab1',
  /** Floor Number Characteristic (0x2AB2) */
  floor_number: '2ab2',
  /** Altitude Characteristic (0x2AB3) */
  altitude: '2ab3',
  /** Uncertainty Characteristic (0x2AB4) */
  uncertainty: '2ab4',
  /** Location Name Characteristic (0x2AB5) */
  location_name: '2ab5',
  /** URI Characteristic (0x2AB6) */
  uri: '2ab6',
  /** HTTP Headers Characteristic (0x2AB7) */
  http_headers: '2ab7',
  /** HTTP Status Code Characteristic (0x2AB8) */
  http_status_code: '2ab8',
  /** HTTP Entity Body Characteristic (0x2AB9) */
  http_entity_body: '2ab9',
  /** HTTP Control Point Characteristic (0x2ABA) */
  http_control_point: '2aba',
  /** HTTPS Security Characteristic (0x2ABB) */
  https_security: '2abb',
  /** TDS Control Point Characteristic (0x2ABC) */
  tds_control_point: '2abc',
  /** OTS Feature Characteristic (0x2ABD) */
  ots_feature: '2abd',
  /** Object Name Characteristic (0x2ABE) */
  object_name: '2abe',
  /** Object Type Characteristic (0x2ABF) */
  object_type: '2abf',
  /** Object Size Characteristic (0x2AC0) */
  object_size: '2ac0',
  /** Object First-Created Characteristic (0x2AC1) */
  object_first_created: '2ac1',
  /** Object Last-Modified Characteristic (0x2AC2) */
  object_last_modified: '2ac2',
  /** Object ID Characteristic (0x2AC3) */
  object_id: '2ac3',
  /** Object Properties Characteristic (0x2AC4) */
  object_properties: '2ac4',
  /** Object Action Control Point Characteristic (0x2AC5) */
  object_action_control_point: '2ac5',
  /** Object List Control Point Characteristic (0x2AC6) */
  object_list_control_point: '2ac6',
  /** Object List Filter Characteristic (0x2AC7) */
  object_list_filter: '2ac7',
  /** Object Changed Characteristic (0x2AC8) */
  object_changed: '2ac8',
  /** Resolvable Private Address Only Characteristic (0x2AC9) */
  resolvable_private_address_only: '2ac9',
  /** Fitness Machine Feature Characteristic (0x2ACC) */
  fitness_machine_feature: '2acc',
  /** Treadmill Data Characteristic (0x2ACD) */
  treadmill_data: '2acd',
  /** Cross Trainer Data Characteristic (0x2ACE) */
  cross_trainer_data: '2ace',
  /** Step Climber Data Characteristic (0x2ACF) */
  step_climber_data: '2acf',
  /** Stair Climber Data Characteristic (0x2AD0) */
  stair_climber_data: '2ad0',
  /** Rower Data Characteristic (0x2AD1) */
  rower_data: '2ad1',
  /** Indoor Bike Data Characteristic (0x2AD2) */
  indoor_bike_data: '2ad2',
  /** Training Status Characteristic (0x2AD3) */
  training_status: '2ad3',
  /** Supported Speed Range Characteristic (0x2AD4) */
  supported_speed_range: '2ad4',
  /** Supported Inclination Range Characteristic (0x2AD5) */
  supported_inclination_range: '2ad5',
  /** Supported Resistance Level Range Characteristic (0x2AD6) */
  supported_resistance_level_range: '2ad6',
  /** Supported Heart Rate Range Characteristic (0x2AD7) */
  supported_heart_rate_range: '2ad7',
  /** Supported Power Range Characteristic (0x2AD8) */
  supported_power_range: '2ad8',
  /** Fitness Machine Control Point Characteristic (0x2AD9) */
  fitness_machine_control_point: '2ad9',
  /** Fitness Machine Status Characteristic (0x2ADA) */
  fitness_machine_status: '2ada',
  /** Mesh Provisioning Data In Characteristic (0x2ADB) */
  mesh_provisioning_data_in: '2adb',
  /** Mesh Provisioning Data Out Characteristic (0x2ADC) */
  mesh_provisioning_data_out: '2adc',
  /** Mesh Proxy Data In Characteristic (0x2ADD) */
  mesh_proxy_data_in: '2add',
  /** Mesh Proxy Data Out Characteristic (0x2ADE) */
  mesh_proxy_data_out: '2ade',
  /** Average Current Characteristic (0x2AE0) */
  average_current: '2ae0',
  /** Average Voltage Characteristic (0x2AE1) */
  average_voltage: '2ae1',
  /** Boolean Characteristic (0x2AE2) */
  boolean: '2ae2',
  /** Chromatic Distance from Planckian Characteristic (0x2AE3) */
  chromatic_distance_from_planckian: '2ae3',
  /** Chromaticity Coordinates Characteristic (0x2AE4) */
  chromaticity_coordinates: '2ae4',
  /** Chromaticity in CCT and Duv Values Characteristic (0x2AE5) */
  chromaticity_in_cct_and_duv_values: '2ae5',
  /** Chromaticity Tolerance Characteristic (0x2AE6) */
  chromaticity_tolerance: '2ae6',
  /** CIE 13.3-1995 Color Rendering Index Characteristic (0x2AE7) */
  cie_13_3_1995_color_rendering_index: '2ae7',
  /** Coefficient Characteristic (0x2AE8) */
  coefficient: '2ae8',
  /** Correlated Color Temperature Characteristic (0x2AE9) */
  correlated_color_temperature: '2ae9',
  /** Count 16 Characteristic (0x2AEA) */
  count_16: '2aea',
  /** Count 24 Characteristic (0x2AEB) */
  count_24: '2aeb',
  /** Country Code Characteristic (0x2AEC) */
  country_code: '2aec',
  /** Date UTC Characteristic (0x2AED) */
  date_utc: '2aed',
  /** Electric Current Characteristic (0x2AEE) */
  electric_current: '2aee',
  /** Electric Current Range Characteristic (0x2AEF) */
  electric_current_range: '2aef',
  /** Electric Current Specification Characteristic (0x2AF0) */
  electric_current_specification: '2af0',
  /** Electric Current Statistics Characteristic (0x2AF1) */
  electric_current_statistics: '2af1',
  /** Energy Characteristic (0x2AF2) */
  energy: '2af2',
  /** Energy in a Period of Day Characteristic (0x2AF3) */
  energy_in_a_period_of_day: '2af3',
  /** Event Statistics Characteristic (0x2AF4) */
  event_statistics: '2af4',
  /** Fixed String 16 Characteristic (0x2AF5) */
  fixed_string_16: '2af5',
  /** Fixed String 24 Characteristic (0x2AF6) */
  fixed_string_24: '2af6',
  /** Fixed String 36 Characteristic (0x2AF7) */
  fixed_string_36: '2af7',
  /** Fixed String 8 Characteristic (0x2AF8) */
  fixed_string_8: '2af8',
  /** Generic Level Characteristic (0x2AF9) */
  generic_level: '2af9',
  /** Global Trade Item Number Characteristic (0x2AFA) */
  global_trade_item_number: '2afa',
  /** Illuminance Characteristic (0x2AFB) */
  illuminance: '2afb',
  /** Luminous Efficacy Characteristic (0x2AFC) */
  luminous_efficacy: '2afc',
  /** Luminous Energy Characteristic (0x2AFD) */
  luminous_energy: '2afd',
  /** Luminous Exposure Characteristic (0x2AFE) */
  luminous_exposure: '2afe',
  /** Luminous Flux Characteristic (0x2AFF) */
  luminous_flux: '2aff',
  /** Luminous Flux Range Characteristic (0x2B00) */
  luminous_flux_range: '2b00',
  /** Luminous Intensity Characteristic (0x2B01) */
  luminous_intensity: '2b01',
  /** Mass Flow Characteristic (0x2B02) */
  mass_flow: '2b02',
  /** Perceived Lightness Characteristic (0x2B03) */
  perceived_lightness: '2b03',
  /** Percentage 8 Characteristic (0x2B04) */
  percentage_8: '2b04',
  /** Power Characteristic (0x2B05) */
  power: '2b05',
  /** Power Specification Characteristic (0x2B06) */
  power_specification: '2b06',
  /** Relative Runtime in a Current Range Characteristic (0x2B07) */
  relative_runtime_in_a_current_range: '2b07',
  /** Relative Runtime in a Generic Level Range Characteristic (0x2B08) */
  relative_runtime_in_a_generic_level_range: '2b08',
  /** Relative Value in a Voltage Range Characteristic (0x2B09) */
  relative_value_in_a_voltage_range: '2b09',
  /** Relative Value in an Illuminance Range Characteristic (0x2B0A) */
  relative_value_in_an_illuminance_range: '2b0a',
  /** Relative Value in a Period of Day Characteristic (0x2B0B) */
  relative_value_in_a_period_of_day: '2b0b',
  /** Relative Value in a Temperature Range Characteristic (0x2B0C) */
  relative_value_in_a_temperature_range: '2b0c',
  /** Temperature 8 Characteristic (0x2B0D) */
  temperature_8: '2b0d',
  /** Temperature 8 in a Period of Day Characteristic (0x2B0E) */
  temperature_8_in_a_period_of_day: '2b0e',
  /** Temperature 8 Statistics Characteristic (0x2B0F) */
  temperature_8_statistics: '2b0f',
  /** Temperature Range Characteristic (0x2B10) */
  temperature_range: '2b10',
  /** Temperature Statistics Characteristic (0x2B11) */
  temperature_statistics: '2b11',
  /** Time Decihour 8 Characteristic (0x2B12) */
  time_decihour_8: '2b12',
  /** Time Exponential 8 Characteristic (0x2B13) */
  time_exponential_8: '2b13',
  /** Time Hour 24 Characteristic (0x2B14) */
  time_hour_24: '2b14',
  /** Time Millisecond 24 Characteristic (0x2B15) */
  time_millisecond_24: '2b15',
  /** Time Second 16 Characteristic (0x2B16) */
  time_second_16: '2b16',
  /** Time Second 8 Characteristic (0x2B17) */
  time_second_8: '2b17',
  /** Voltage Characteristic (0x2B18) */
  voltage: '2b18',
  /** Voltage Specification Characteristic (0x2B19) */
  voltage_specification: '2b19',
  /** Voltage Statistics Characteristic (0x2B1A) */
  voltage_statistics: '2b1a',
  /** Volume Flow Characteristic (0x2B1B) */
  volume_flow: '2b1b',
  /** Chromaticity Coordinate Characteristic (0x2B1C) */
  chromaticity_coordinate: '2b1c',
  /** RC Feature Characteristic (0x2B1D) */
  rc_feature: '2b1d',
  /** RC Settings Characteristic (0x2B1E) */
  rc_settings: '2b1e',
  /** Reconnection Configuration Control Point Characteristic (0x2B1F) */
  reconnection_configuration_control_point: '2b1f',
  /** IDD Status Changed Characteristic (0x2B20) */
  idd_status_changed: '2b20',
  /** IDD Status Characteristic (0x2B21) */
  idd_status: '2b21',
  /** IDD Annunciation Status Characteristic (0x2B22) */
  idd_annunciation_status: '2b22',
  /** IDD Features Characteristic (0x2B23) */
  idd_features: '2b23',
  /** IDD Status Reader Control Point Characteristic (0x2B24) */
  idd_status_reader_control_point: '2b24',
  /** IDD Command Control Point Characteristic (0x2B25) */
  idd_command_control_point: '2b25',
  /** IDD Command Data Characteristic (0x2B26) */
  idd_command_data: '2b26',
  /** IDD Record Access Control Point Characteristic (0x2B27) */
  idd_record_access_control_point: '2b27',
  /** IDD History Data Characteristic (0x2B28) */
  idd_history_data: '2b28',
  /** Client Supported Features Characteristic (0x2B29) */
  client_supported_features: '2b29',
  /** Database Hash Characteristic (0x2B2A) */
  database_hash: '2b2a',
  /** BSS Control Point Characteristic (0x2B2B) */
  bss_control_point: '2b2b',
  /** BSS Response Characteristic (0x2B2C) */
  bss_response: '2b2c',
  /** Emergency ID Characteristic (0x2B2D) */
  emergency_id: '2b2d',
  /** Emergency Text Characteristic (0x2B2E) */
  emergency_text: '2b2e',
  /** ACS Status Characteristic (0x2B2F) */
  acs_status: '2b2f',
  /** ACS Data In Characteristic (0x2B30) */
  acs_data_in: '2b30',
  /** ACS Data Out Notify Characteristic (0x2B31) */
  acs_data_out_notify: '2b31',
  /** ACS Data Out Indicate Characteristic (0x2B32) */
  acs_data_out_indicate: '2b32',
  /** ACS Control Point Characteristic (0x2B33) */
  acs_control_point: '2b33',
  /** Enhanced Blood Pressure Measurement Characteristic (0x2B34) */
  enhanced_blood_pressure_measurement: '2b34',
  /** Enhanced Intermediate Cuff Pressure Characteristic (0x2B35) */
  enhanced_intermediate_cuff_pressure: '2b35',
  /** Blood Pressure Record Characteristic (0x2B36) */
  blood_pressure_record: '2b36',
  /** Registered User Characteristic (0x2B37) */
  registered_user: '2b37',
  /** BR-EDR Handover Data Characteristic (0x2B38) */
  br_edr_handover_data: '2b38',
  /** Bluetooth SIG Data Characteristic (0x2B39) */
  bluetooth_sig_data: '2b39',
  /** Server Supported Features Characteristic (0x2B3A) */
  server_supported_features: '2b3a',
  /** Physical Activity Monitor Features Characteristic (0x2B3B) */
  physical_activity_monitor_features: '2b3b',
  /** General Activity Instantaneous Data Characteristic (0x2B3C) */
  general_activity_instantaneous_data: '2b3c',
  /** General Activity Summary Data Characteristic (0x2B3D) */
  general_activity_summary_data: '2b3d',
  /** CardioRespiratory Activity Instantaneous Data Characteristic (0x2B3E) */
  cardiorespiratory_activity_instantaneous_data: '2b3e',
  /** CardioRespiratory Activity Summary Data Characteristic (0x2B3F) */
  cardiorespiratory_activity_summary_data: '2b3f',
  /** Step Counter Activity Summary Data Characteristic (0x2B40) */
  step_counter_activity_summary_data: '2b40',
  /** Sleep Activity Instantaneous Data Characteristic (0x2B41) */
  sleep_activity_instantaneous_data: '2b41',
  /** Sleep Activity Summary Data Characteristic (0x2B42) */
  sleep_activity_summary_data: '2b42',
  /** Physical Activity Monitor Control Point Characteristic (0x2B43) */
  physical_activity_monitor_control_point: '2b43',
  /** Activity Current Session Characteristic (0x2B44) */
  activity_current_session: '2b44',
  /** Physical Activity Session Descriptor Characteristic (0x2B45) */
  physical_activity_session_descriptor: '2b45',
  /** Preferred Units Characteristic (0x2B46) */
  preferred_units: '2b46',
  /** High Resolution Height Characteristic (0x2B47) */
  high_resolution_height: '2b47',
  /** Middle Name Characteristic (0x2B48) */
  middle_name: '2b48',
  /** Stride Length Characteristic (0x2B49) */
  stride_length: '2b49',
  /** Handedness Characteristic (0x2B4A) */
  handedness: '2b4a',
  /** Device Wearing Position Characteristic (0x2B4B) */
  device_wearing_position: '2b4b',
  /** Four Zone Heart Rate Limits Characteristic (0x2B4C) */
  four_zone_heart_rate_limits: '2b4c',
  /** High Intensity Exercise Threshold Characteristic (0x2B4D) */
  high_intensity_exercise_threshold: '2b4d',
  /** Activity Goal Characteristic (0x2B4E) */
  activity_goal: '2b4e',
  /** Sedentary Interval Notification Characteristic (0x2B4F) */
  sedentary_interval_notification: '2b4f',
  /** Caloric Intake Characteristic (0x2B50) */
  caloric_intake: '2b50',
  /** TMAP Role Characteristic (0x2B51) */
  tmap_role: '2b51',
  /** Audio Input State Characteristic (0x2B77) */
  audio_input_state: '2b77',
  /** Gain Settings Attribute Characteristic (0x2B78) */
  gain_settings_attribute: '2b78',
  /** Audio Input Type Characteristic (0x2B79) */
  audio_input_type: '2b79',
  /** Audio Input Status Characteristic (0x2B7A) */
  audio_input_status: '2b7a',
  /** Audio Input Control Point Characteristic (0x2B7B) */
  audio_input_control_point: '2b7b',
  /** Audio Input Description Characteristic (0x2B7C) */
  audio_input_description: '2b7c',
  /** Volume State Characteristic (0x2B7D) */
  volume_state: '2b7d',
  /** Volume Control Point Characteristic (0x2B7E) */
  volume_control_point: '2b7e',
  /** Volume Flags Characteristic (0x2B7F) */
  volume_flags: '2b7f',
  /** Volume Offset State Characteristic (0x2B80) */
  volume_offset_state: '2b80',
  /** Audio Location Characteristic (0x2B81) */
  audio_location: '2b81',
  /** Volume Offset Control Point Characteristic (0x2B82) */
  volume_offset_control_point: '2b82',
  /** Audio Output Description Characteristic (0x2B83) */
  audio_output_description: '2b83',
  /** Set Identity Resolving Key Characteristic (0x2B84) */
  set_identity_resolving_key: '2b84',
  /** Coordinated Set Size Characteristic (0x2B85) */
  size_characteristic: '2b85',
  /** Set Member Lock Characteristic (0x2B86) */
  lock_characteristic: '2b86',
  /** Set Member Rank Characteristic (0x2B87) */
  rank_characteristic: '2b87',
  /** Encrypted Data Key Material Characteristic (0x2B88) */
  encrypted_data_key_material: '2b88',
  /** Apparent Energy 32 Characteristic (0x2B89) */
  apparent_energy_32: '2b89',
  /** Apparent Power Characteristic (0x2B8A) */
  apparent_power: '2b8a',
  /** Live Health Observations Characteristic (0x2B8B) */
  live_health_observations: '2b8b',
  /** CO\textsubscript{2} Concentration Characteristic (0x2B8C) */
  co2_concentration: '2b8c',
  /** Cosine of the Angle Characteristic (0x2B8D) */
  cosine_of_the_angle: '2b8d',
  /** Device Time Feature Characteristic (0x2B8E) */
  device_time_feature: '2b8e',
  /** Device Time Parameters Characteristic (0x2B8F) */
  device_time_parameters: '2b8f',
  /** Device Time Characteristic (0x2B90) */
  device_time: '2b90',
  /** Device Time Control Point Characteristic (0x2B91) */
  device_time_control_point: '2b91',
  /** Time Change Log Data Characteristic (0x2B92) */
  time_change_log_data: '2b92',
  /** Media Player Name Characteristic (0x2B93) */
  media_player_name: '2b93',
  /** Media Player Icon Object ID Characteristic (0x2B94) */
  media_player_icon_object_id: '2b94',
  /** Media Player Icon URL Characteristic (0x2B95) */
  media_player_icon_url: '2b95',
  /** Track Changed Characteristic (0x2B96) */
  track_changed: '2b96',
  /** Track Title Characteristic (0x2B97) */
  track_title: '2b97',
  /** Track Duration Characteristic (0x2B98) */
  track_duration: '2b98',
  /** Track Position Characteristic (0x2B99) */
  track_position: '2b99',
  /** Playback Speed Characteristic (0x2B9A) */
  playback_speed: '2b9a',
  /** Seeking Speed Characteristic (0x2B9B) */
  seeking_speed: '2b9b',
  /** Current Track Segments Object ID Characteristic (0x2B9C) */
  current_track_segments_object_id: '2b9c',
  /** Current Track Object ID Characteristic (0x2B9D) */
  current_track_object_id: '2b9d',
  /** Next Track Object ID Characteristic (0x2B9E) */
  next_track_object_id: '2b9e',
  /** Parent Group Object ID Characteristic (0x2B9F) */
  parent_group_object_id: '2b9f',
  /** Current Group Object ID Characteristic (0x2BA0) */
  current_group_object_id: '2ba0',
  /** Playing Order Characteristic (0x2BA1) */
  playing_order: '2ba1',
  /** Playing Orders Supported Characteristic (0x2BA2) */
  playing_orders_supported: '2ba2',
  /** Media State Characteristic (0x2BA3) */
  media_state: '2ba3',
  /** Media Control Point Characteristic (0x2BA4) */
  media_control_point: '2ba4',
  /** Media Control Point Opcodes Supported Characteristic (0x2BA5) */
  media_control_point_opcodes_supported: '2ba5',
  /** Search Results Object ID Characteristic (0x2BA6) */
  search_results_object_id: '2ba6',
  /** Search Control Point Characteristic (0x2BA7) */
  search_control_point: '2ba7',
  /** Energy 32 Characteristic (0x2BA8) */
  energy_32: '2ba8',
  /** Media Player Icon Object Type Characteristic (0x2BA9) */
  media_player_icon_object_type: '2ba9',
  /** Track Segments Object Type Characteristic (0x2BAA) */
  track_segments_object_type: '2baa',
  /** Track Object Type Characteristic (0x2BAB) */
  track_object_type: '2bab',
  /** Group Object Type Characteristic (0x2BAC) */
  group_object_type: '2bac',
  /** Constant Tone Extension Enable Characteristic (0x2BAD) */
  constant_tone_extension_enable: '2bad',
  /** Advertising Constant Tone Extension Minimum Length Characteristic (0x2BAE) */
  advertising_constant_tone_extension_minimum_length: '2bae',
  /** Advertising Constant Tone Extension Minimum Transmit Count Characteristic (0x2BAF) */
  advertising_constant_tone_extension_minimum_transmit_count: '2baf',
  /** Advertising Constant Tone Extension Transmit Duration Characteristic (0x2BB0) */
  advertising_constant_tone_extension_transmit_duration: '2bb0',
  /** Advertising Constant Tone Extension Interval Characteristic (0x2BB1) */
  advertising_constant_tone_extension_interval: '2bb1',
  /** Advertising Constant Tone Extension PHY Characteristic (0x2BB2) */
  advertising_constant_tone_extension_phy: '2bb2',
  /** Bearer Provider Name Characteristic (0x2BB3) */
  bearer_provider_name: '2bb3',
  /** Bearer UCI Characteristic (0x2BB4) */
  bearer_uci: '2bb4',
  /** Bearer Technology Characteristic (0x2BB5) */
  bearer_technology: '2bb5',
  /** Bearer URI Schemes Supported List Characteristic (0x2BB6) */
  bearer_uri_schemes_supported_list: '2bb6',
  /** Bearer Signal Strength Characteristic (0x2BB7) */
  bearer_signal_strength: '2bb7',
  /** Bearer Signal Strength Reporting Interval Characteristic (0x2BB8) */
  bearer_signal_strength_reporting_interval: '2bb8',
  /** Bearer List Current Calls Characteristic (0x2BB9) */
  bearer_list_current_calls: '2bb9',
  /** Content Control ID Characteristic (0x2BBA) */
  content_control_id: '2bba',
  /** Status Flags Characteristic (0x2BBB) */
  status_flags: '2bbb',
  /** Incoming Call Target Bearer URI Characteristic (0x2BBC) */
  incoming_call_target_bearer_uri: '2bbc',
  /** Call State Characteristic (0x2BBD) */
  call_state: '2bbd',
  /** Call Control Point Characteristic (0x2BBE) */
  call_control_point: '2bbe',
  /** Call Control Point Optional Opcodes Characteristic (0x2BBF) */
  call_control_point_optional_opcodes: '2bbf',
  /** Termination Reason Characteristic (0x2BC0) */
  termination_reason: '2bc0',
  /** Incoming Call Characteristic (0x2BC1) */
  incoming_call: '2bc1',
  /** Call Friendly Name Characteristic (0x2BC2) */
  call_friendly_name: '2bc2',
  /** Mute Characteristic (0x2BC3) */
  mute: '2bc3',
  /** Sink ASE Characteristic (0x2BC4) */
  sink_ase: '2bc4',
  /** Source ASE Characteristic (0x2BC5) */
  source_ase: '2bc5',
  /** ASE Control Point Characteristic (0x2BC6) */
  ase_control_point: '2bc6',
  /** Broadcast Audio Scan Control Point Characteristic (0x2BC7) */
  broadcast_audio_scan_control_point: '2bc7',
  /** Broadcast Receive State Characteristic (0x2BC8) */
  broadcast_receive_state: '2bc8',
  /** Sink PAC Characteristic (0x2BC9) */
  sink_pac: '2bc9',
  /** Sink Audio Locations Characteristic (0x2BCA) */
  sink_audio_locations: '2bca',
  /** Source PAC Characteristic (0x2BCB) */
  source_pac: '2bcb',
  /** Source Audio Locations Characteristic (0x2BCC) */
  source_audio_locations: '2bcc',
  /** Available Audio Contexts Characteristic (0x2BCD) */
  available_audio_contexts: '2bcd',
  /** Supported Audio Contexts Characteristic (0x2BCE) */
  supported_audio_contexts: '2bce',
  /** Ammonia Concentration Characteristic (0x2BCF) */
  ammonia_concentration: '2bcf',
  /** Carbon Monoxide Concentration Characteristic (0x2BD0) */
  carbon_monoxide_concentration: '2bd0',
  /** Methane Concentration Characteristic (0x2BD1) */
  methane_concentration: '2bd1',
  /** Nitrogen Dioxide Concentration Characteristic (0x2BD2) */
  nitrogen_dioxide_concentration: '2bd2',
  /** Non-Methane Volatile Organic Compounds Concentration Characteristic (0x2BD3) */
  non_methane_volatile_organic_compounds_concentration: '2bd3',
  /** Ozone Concentration Characteristic (0x2BD4) */
  ozone_concentration: '2bd4',
  /** Particulate Matter - PM1 Concentration Characteristic (0x2BD5) */
  particulate_matter_pm1_concentration: '2bd5',
  /** Particulate Matter - PM2.5 Concentration Characteristic (0x2BD6) */
  particulate_matter_pm2_5_concentration: '2bd6',
  /** Particulate Matter - PM10 Concentration Characteristic (0x2BD7) */
  particulate_matter_pm10_concentration: '2bd7',
  /** Sulfur Dioxide Concentration Characteristic (0x2BD8) */
  sulfur_dioxide_concentration: '2bd8',
  /** Sulfur Hexafluoride Concentration Characteristic (0x2BD9) */
  sulfur_hexafluoride_concentration: '2bd9',
  /** Hearing Aid Features Characteristic (0x2BDA) */
  hearing_aid_features: '2bda',
  /** Hearing Aid Preset Control Point Characteristic (0x2BDB) */
  hearing_aid_preset_control_point: '2bdb',
  /** Active Preset Index Characteristic (0x2BDC) */
  active_preset_index: '2bdc',
  /** Stored Health Observations Characteristic (0x2BDD) */
  stored_health_observations: '2bdd',
  /** Fixed String 64 Characteristic (0x2BDE) */
  fixed_string_64: '2bde',
  /** High Temperature Characteristic (0x2BDF) */
  high_temperature: '2bdf',
  /** High Voltage Characteristic (0x2BE0) */
  high_voltage: '2be0',
  /** Light Distribution Characteristic (0x2BE1) */
  light_distribution: '2be1',
  /** Light Output Characteristic (0x2BE2) */
  light_output: '2be2',
  /** Light Source Type Characteristic (0x2BE3) */
  light_source_type: '2be3',
  /** Noise Characteristic (0x2BE4) */
  noise: '2be4',
  /** Relative Runtime in a Correlated Color Temperature Range Characteristic (0x2BE5) */
  relative_runtime_in_a_correlated_color_temperature_range: '2be5',
  /** Time Second 32 Characteristic (0x2BE6) */
  time_second_32: '2be6',
  /** VOC Concentration Characteristic (0x2BE7) */
  voc_concentration: '2be7',
  /** Voltage Frequency Characteristic (0x2BE8) */
  voltage_frequency: '2be8',
  /** Battery Critical Status Characteristic (0x2BE9) */
  battery_critical_status: '2be9',
  /** Battery Health Status Characteristic (0x2BEA) */
  battery_health_status: '2bea',
  /** Battery Health Information Characteristic (0x2BEB) */
  battery_health_information: '2beb',
  /** Battery Information Characteristic (0x2BEC) */
  battery_information: '2bec',
  /** Battery Level Status Characteristic (0x2BED) */
  battery_level_status: '2bed',
  /** Battery Time Status Characteristic (0x2BEE) */
  battery_time_status: '2bee',
  /** Estimated Service Date Characteristic (0x2BEF) */
  estimated_service_date: '2bef',
  /** Battery Energy Status Characteristic (0x2BF0) */
  battery_energy_status: '2bf0',
  /** Observation Schedule Changed Characteristic (0x2BF1) */
  observation_schedule_changed: '2bf1',
  /** Current Elapsed Time Characteristic (0x2BF2) */
  current_elapsed_time: '2bf2',
  /** Health Sensor Features Characteristic (0x2BF3) */
  health_sensor_features: '2bf3',
  /** GHS Control Point Characteristic (0x2BF4) */
  ghs_control_point: '2bf4',
  /** LE GATT Security Levels Characteristic (0x2BF5) */
  le_gatt_security_levels: '2bf5',
  /** ESL Address Characteristic (0x2BF6) */
  esl_address: '2bf6',
  /** AP Sync Key Material Characteristic (0x2BF7) */
  ap_sync_key_material: '2bf7',
  /** ESL Response Key Material Characteristic (0x2BF8) */
  esl_response_key_material: '2bf8',
  /** ESL Current Absolute Time Characteristic (0x2BF9) */
  esl_current_absolute_time: '2bf9',
  /** ESL Display Information Characteristic (0x2BFA) */
  esl_display_information: '2bfa',
  /** ESL Image Information Characteristic (0x2BFB) */
  esl_image_information: '2bfb',
  /** ESL Sensor Information Characteristic (0x2BFC) */
  esl_sensor_information: '2bfc',
  /** ESL LED Information Characteristic (0x2BFD) */
  esl_led_information: '2bfd',
  /** ESL Control Point Characteristic (0x2BFE) */
  esl_control_point: '2bfe',
  /** UDI for Medical Devices Characteristic (0x2BFF) */
  medical_devices: '2bff',
} as const;
